name: Auto-update event galleries and index

on:
  push:
    paths:
      - 'pics/**'

permissions:
  contents: write

jobs:
  update-galleries-and-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Generate event JSONs and HTML galleries
        run: |
          # Collect events
          events=()
          for event_dir in pics/*; do
            if [ -d "$event_dir" ]; then
              event=$(basename "$event_dir")
              events+=("$event")
              jsonfile="$event.json"
              htmlfile="$event.html"
              imglist=()
              for imgfile in "$event_dir"/*.{jpg,jpeg,png,gif,bmp,webp}; do
                [ -e "$imgfile" ] || continue
                imglist+=("\"$(basename "$imgfile")\"")
              done
              # Write image list JSON file
              echo "[${imglist[*]}]" > "$jsonfile"

              # Create event gallery HTML file
              cat > "$htmlfile" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width
