name: Update event JSONs

on:
  push:
    paths:
      - 'pics/**'

permissions:
  contents: write

jobs:
  event-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create event JSON files
        run: |
          for event_dir in pics/*; do
            if [ -d "$event_dir" ]; then
              event=$(basename "$event_dir")
              jsonfile="${event}.json"
              imglist=()
              for imgfile in "$event_dir"/*.{jpg,jpeg,png,gif,bmp,webp}; do
                [ -e "$imgfile" ] || continue
                imglist+=("\"$(basename "$imgfile")\"")
              done
              echo "[${imglist[*]}]" > "$jsonfile"
            fi
          done
      - name: Commit JSONs
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.json
          git commit -m "Update event JSON files" || exit 0
          git push
